Question 5: <br>
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. (20 points)<br>
Example:
+ nums1 = [1, 3, 6]; nums2 = [1, 2, 10] => Merged array: [1, 1, 2, 3, 6, 10]. Median is (2 + 3)/2 = 2,5.
+ nums1 = [1, 3]; nums2 = [1, 2, 10] => Merged array: [1, 1, 2, 6, 10]. Median is 2.


<em><u> Lời giải: </u></em> <br>
Bước 1: Gộp hai mảng lại <br>
Bước 2: Theo tổng độ dài hai mảng có hai trường hợp: <br>
+ Lẻ: lấy phần tử ở vị trí 1/2*(tổng độ dài hai mảng) làm trung vị
+ Chẵn: lấy trung bình của tổng 2 phần tử: phần tử ở vị trí 1/2*(tổng độ dài hai mảng) và 1/2*(tổng độ dài hai mảng) - 1 làm trung vị. <br> <br>
Độ phức tạp thuật toán O(n) gồm hai lần duyệt để gộp mảng O(m) + O(n) = O(m + n).

In [2]:
import random
import numpy as np

In [55]:
def med(a,b):
    c = np.sort(np.concatenate((a,b)),kind = "mergesort")
    if len(c) % 2 == 0:
        print((c[int(len(c)/2)] + c[int(len(c)/2)-1])/2)
    else:
        print(c[int(len(c)/2)])

In [61]:
a = np.sort(np.array(random.sample(range(100),8)))
b = np.sort(np.array(random.sample(range(100),9)))

In [62]:
a

array([42, 54, 58, 62, 76, 78, 83, 98])

In [63]:
b

array([38, 51, 56, 58, 65, 67, 77, 93, 96])

In [64]:
med(a,b)

65


In [65]:
c = np.sort(np.concatenate((a,b)),kind = "mergesort")
print(c)
np.median(c)

[38 42 51 54 56 58 58 62 65 67 76 77 78 83 93 96 98]


65.0